services:
  simulator:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "50051:50051"
      - "50052:50052"
      - "50053:50053"
      - "50054:50054"
    container_name: dbr-simulator
    restart: unless-stopped
    environment:
      ROOT_DIR: /root