services:
  simulator:
    platform: linux/amd64
    image: aydanpirani/dbr-simulator:latest
    ports:
      - "50051:50051"
      - "50052:50052"
      - "50053:50053"
      - "50054:50054"
    restart: unless-stopped
    environment:
      ROOT_DIR: /root
    deploy:
      mode: global
    hostname: "{{.Node.Hostname}}"
