# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: database.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'database.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tabase.proto\x12\x08\x64\x61tabase\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\x0c\"\x19\n\x08GetReply\x12\r\n\x05value\x18\x01 \x01(\x0c\"(\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c\"\x1b\n\x08SetReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1c\n\rRegionRequest\x12\x0b\n\x03key\x18\x01 \x01(\x0c\"\"\n\x0fReadRegionReply\x12\x0f\n\x07regions\x18\x01 \x03(\t\"\"\n\x10WriteRegionReply\x12\x0e\n\x06region\x18\x01 \x01(\t\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c\x32\xb3\x02\n\x08\x44\x61tabase\x12\x38\n\x08SayHello\x12\x16.database.HelloRequest\x1a\x14.database.HelloReply\x12/\n\x03Get\x12\x14.database.GetRequest\x1a\x12.database.GetReply\x12/\n\x03Set\x12\x14.database.SetRequest\x1a\x12.database.SetReply\x12\x44\n\x0eGetReadRegions\x12\x17.database.RegionRequest\x1a\x19.database.ReadRegionReply\x12\x45\n\x0eGetWriteRegion\x12\x17.database.RegionRequest\x1a\x1a.database.WriteRegionReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=28
  _globals['_HELLOREQUEST']._serialized_end=56
  _globals['_HELLOREPLY']._serialized_start=58
  _globals['_HELLOREPLY']._serialized_end=87
  _globals['_GETREQUEST']._serialized_start=89
  _globals['_GETREQUEST']._serialized_end=114
  _globals['_GETREPLY']._serialized_start=116
  _globals['_GETREPLY']._serialized_end=141
  _globals['_SETREQUEST']._serialized_start=143
  _globals['_SETREQUEST']._serialized_end=183
  _globals['_SETREPLY']._serialized_start=185
  _globals['_SETREPLY']._serialized_end=212
  _globals['_REGIONREQUEST']._serialized_start=214
  _globals['_REGIONREQUEST']._serialized_end=242
  _globals['_READREGIONREPLY']._serialized_start=244
  _globals['_READREGIONREPLY']._serialized_end=278
  _globals['_WRITEREGIONREPLY']._serialized_start=280
  _globals['_WRITEREGIONREPLY']._serialized_end=314
  _globals['_KEYVALUE']._serialized_start=316
  _globals['_KEYVALUE']._serialized_end=354
  _globals['_DATABASE']._serialized_start=357
  _globals['_DATABASE']._serialized_end=664
# @@protoc_insertion_point(module_scope)
